{% set version = "0.2.0" %}

package:
  name: fluidimage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fluidimage/fluidimage-{{ version }}.tar.gz
  sha256: 55b3b118ea16f72b00e9f51e9635fbae242751bbdde60e29ad6fdb5cc7274135

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - fluidimviewer-pg = fluidimage.gui.pg_main:main
    - fluidimviewer = fluidimage.gui.imviewer:main
    - fluidimlauncher = fluidimage.gui.launcher.main:main
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - meson-python
    - numpy
    - transonic =0.6.1
    - pythran >=0.9.7
    # pythran code needs clang-cl on windows
    - clang  # [win]
  run:
    - python
    - ipython
    - {{ pin_compatible('numpy') }}
    - transonic =0.6.1
    - dask
    - fluiddyn >=0.3.4
    - h5netcdf
    - h5py
    - imageio
    - matplotlib-base
    - pims
    - pyfftw >=0.10.4
    - scipy >=0.14.1
    - trio
    - opencv
    - scikit-image >=0.12.3

test:
  imports:
    - fluidimage
    - fluidimage.calcul
    - fluidimage.calcul.interpolate
    - fluidimage.calibration
    - fluidimage.data_objects
    - fluidimage.executors
    - fluidimage.gui
    - fluidimage.gui.launcher
    - fluidimage.postproc
    - fluidimage.preproc
    - fluidimage.reconstruct
    - fluidimage.topologies
    - fluidimage.util
    - fluidimage.works
    - fluidimage.works.piv
  commands:
    - fluidimviewer-pg --help
    - fluidimviewer --help
    # - fluidimlauncher -h

about:
  home: https://foss.heptapod.net/fluiddyn/fluidimage
  license: LicenseRef-CeCILL-B
  license_file: LICENSE.txt
  summary: libre Python framework for scientific processing of large series of images.
  description: |
    This package is young but already good enough to be used “in production”
    to display and pre-process images, compute displacement or velocity fields
    with Particle Image Velocimetry (PIV, i.e. displacements of pattern
    obtained by correlations of cropped images) and optical flow, analyze and
    display PIV fields.

  doc_url: https://fluidimage.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
