travis:
  secure:
    BINSTAR_TOKEN: qzK1jk8SLH+L43h3mlkfUa5wtPR7wXOWjjxBj+T9r2TGfMXYG9SJJK+mJ/4krIxLuG2IAgAfVwycWGt01qZEmC2ccS2zPwFsua0wovtVVEEnZ7+etfmqFdwr/u3FLHpGtOZ0XJaWQ7n6XCi9qzAMBd8o8j3rfk0kQuIVEMc1k0z2Rgmy3VE8i1SrfT2Fe4PiFFawzZMi9MYXmFfERl5ypUhdr7NxbHHlK/GbcaeStNd9TEzvizBRMEaKwq2nDX/m6KB3OcACCN6duepdjLlTsQpS9npfDp75FLWIbB9gv4Ed1Un/r7EDkWBYpxkasO5t7E5gcMYQ6XuZ0rrKHCRn0qZ9/jMBm8RRc6XMZn892c7Wbf7puPG+zKR8DQQ4PY1G4Q2eMLrzNaFfTq73pIObN8dHqH1//uD6bjY69+scCviCEIYfdDkz73nwCnEyDPF9pa/0WVlZHQUvnW+PAoz/zmb0OE84EwdqnF+LCS1PXo5y9Kn8+fsRgEV67vmM2n1DbsfSb/3sWm4iXKt8EvawgwqBcX5f/nOiuvx1PYHbCyJlFdOvsU3PuwPqzlghD4p9s+xqawbRDfcHxV6hWG7IaRLR1NertvRGEFF4/j4JBlkYk/Jv24Ap6TatAmfnGSTY6HmCltp96Ybj9VgVbHqXS1hV2bEOy8pg01/JzmjK8V4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
